services:

  web:
    image: paperless-rest
    build:
      context: .
      dockerfile: Web/Dockerfile
      target: debug
    ports:
     - "8081:8081"
     - "5005:5005" # remote debugging
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081
      - DOTNET_USE_POLLING_FILE_WATCHER=1  # hot reload for debugging
      - ASPNETCORE_REMOTE_DEBUGGING=5005   # port for debugging
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./src:/app
      - ./uploads:/app/uploads

 
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: karo
      RABBITMQ_DEFAULT_PASS: karo

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - ./Web/wwwroot/nginx.conf:/etc/nginx/nginx.conf
      - ./Web/wwwroot/html:/usr/share/nginx/html
    depends_on:
      - web

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: karo
      POSTGRES_PASSWORD: karo
      POSTGRES_DB: dmsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: karo@karo.com
      PGADMIN_DEFAULT_PASSWORD: karo
    ports:
      - "5050:80"
    depends_on:
      - postgres

  ocr_worker:
     image: ocr_worker_image
     build:
       context: ./OcrWorker  
       dockerfile: Dockerfile
     depends_on:
       - rabbitmq
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     volumes:
       - ./uploads:/app/uploads

volumes:
  postgres-data:  