services:

  web:
    image: paperless-rest
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
     - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - ./Web/wwwroot/nginx.conf:/etc/nginx/nginx.conf
      - ./Web/wwwroot/html:/usr/share/nginx/html
    depends_on:
      - web
