services:

  web:
    image: paperless-rest
    build:
      context: .
      dockerfile: Web/Dockerfile
      target: debug
    ports:
     - "8081:8081"
     - "5005:5005" # remote debugging
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081
      - DOTNET_USE_POLLING_FILE_WATCHER=1  # hot reload for debugging
      - ASPNETCORE_REMOTE_DEBUGGING=5005   # port for debugging
    depends_on:
      - postgres
    volumes:
      - ./src:/app

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - ./Web/wwwroot/nginx.conf:/etc/nginx/nginx.conf
      - ./Web/wwwroot/html:/usr/share/nginx/html
    depends_on:
      - web

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: karo
      POSTGRES_PASSWORD: karo
      POSTGRES_DB: dmsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: karo@karo.com
      PGADMIN_DEFAULT_PASSWORD: karo
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data: